name: Go

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Ensure go.mod and go.sum are tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum
      - name: Run Go Vet
        run: go vet ./...
      - name: Run Staticcheck
        # v2025.1.1, see: https://github.com/dominikh/go-tools/commit/b8ec13ce4d00445d75da053c47498e6f9ec5d7d6
        run: go run honnef.co/go/tools/cmd/staticcheck@b8ec13ce4d00445d75da053c47498e6f9ec5d7d6 ./...
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Run tests
        run: go test ./...